"""make ai fields nullable on flagged_orders

Revision ID: 5592b3102c27
Revises: 9de0a99c5692
Create Date: 2026-09-04 11:29:16.475419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5592b3102c27'
down_revision: Union[str, Sequence[str], None] = '9de0a99c5692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flagged_orders', 'ai_explanation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('flagged_orders', 'ai_draft_message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flagged_orders', 'ai_draft_message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('flagged_orders', 'ai_explanation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
