"""create initial tables

Revision ID: 9de0a99c5692
Revises: 
Create Date: 2026-09-04 10:11:46.619250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9de0a99c5692'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_domain', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=False),
    sa.Column('installed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('uninstalled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_shop_domain'), 'shops', ['shop_domain'], unique=True)
    op.create_table('flagged_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('shopify_order_id', sa.String(length=64), nullable=False),
    sa.Column('order_number', sa.String(length=64), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('order_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('flagged_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('threshold_crossed_at', sa.DateTime(), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('ai_explanation', sa.String(), nullable=False),
    sa.Column('ai_draft_message', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flagged_orders_shop_id'), 'flagged_orders', ['shop_id'], unique=False)
    op.create_table('settings',
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('threshold_hours', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('shop_id')
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('shopify_webhook_id', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_shop_id'), 'webhook_events', ['shop_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_shopify_webhook_id'), 'webhook_events', ['shopify_webhook_id'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('flagged_order_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flagged_order_id'], ['flagged_orders.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_shop_id'), 'audit_log', ['shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_shop_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_webhook_events_shopify_webhook_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_shop_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_table('settings')
    op.drop_index(op.f('ix_flagged_orders_shop_id'), table_name='flagged_orders')
    op.drop_table('flagged_orders')
    op.drop_index(op.f('ix_shops_shop_domain'), table_name='shops')
    op.drop_table('shops')
    # ### end Alembic commands ###
